### ISSUE TITLE
Standardizing Pano credentials

### ISSUE THREAD

**Issue by achafetz** [USAID-OHA-SI/grabr#44]
In trying to test out `pano_content()`, I got an error that this is now taking new credentials, switching from `session` to `username` and `password`. Some of the `pano_*` functions take one or the other. I think we should shore this up for better consistence. To create the session, you need to add the username and password, but should we just use the session for everything else?

| function          | user + pwd | session | none |
|-------------------|------------|---------|------|
| pano_session      |      X     |         |      |
| pano_content      |            |    X    |      |
| pano_download     |            |    X    |      |
| pano_elements     |            |         |   X  |
| pano_extract      |      X     |         |      |
| pano_extract_msd  |      X     |         |      |
| pano_extract_msds |      X     |         |      |
| pano_items        |            |    X    |      |
| pano_unpack       |            |    X    |      |

**Comment by baboyma** [comment]
`pano_session()`, `pano_content()` and `pano_elements()` should now be hidden to users. They are used as internal functions where the session is a pass through. `pano_items()` was updated to use user/pass.

Good catch on the `pano_download()`. The initial design was to get all pano data items and then downlaod targeted files. We then came up with pono_extract and pano_extract_* as wrapper functions with pano_download() embeded - that's why it uses a session. download function can also be hidden or we will need to pass user/pass.
